title: The Murphy Home
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Home Overview
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Modes
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - input_boolean.disable_home_away
          - input_boolean.vacation_mode
          - input_select.holiday

        # The markdown card will render markdown text.
      - type: entities
        title: Batteries
        entities:
          - sensor.zooz_motion_battery
          - sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_battery_level
          - sensor.dinning_door_battery
          - sensor.dryer_shock_battery
          - sensor.basement_thermostat_battery
      - type: entities
        title: Household
        entities:
          - device_tracker.wife_iphone
          - device_tracker.me_phone
          - group.people
      - type: entity-filter
        entities:
          - switch.basement_stairs
          - switch.basement_stairs_motion
          - light.living_room
          - switch.68102802dc4f22ef95b7
          - light.kids_light
          - light.front_door
          - light.stove_light
          - light.office_desk_lamp
          - switch.master_bedroom_closet
          - switch.ge_26931_smart_motion_switch_switch_4
          - switch.outdoor_right_yard
        state_filter:
          - "on"
        card: 
          type: glance
          title: Lights On
      - type: entity-filter
        entities:
          - switch.68102802dc4f22e873fa
        state_filter:
          - "on"
        card: 
          type: glance
          title: Outlet On
      # - type: picture-entity
          # entity: sensor.plex
          # name: Plex
          # image: /config/www/plex.png
  - title: Living Room
    cards:
      - type: entities
        title: Lights
        entities:
          - light.living_room
          - switch.68102802dc4f22ef95b7
      - type: glance
        title: Living Room TV
        entities:
          - binary_sensor.livingroom_tv
      - type: media-control
        title: Living Room Chromecast
        entity: media_player.living_room_tv 
      - type: media-control
        title: Samsung TV
        entity: media_player.samsung_tv_remote
  - title: Kitchen
    cards:
      - type: entities
        title: Entities
        entities:
          - light.stove_light
  - title: Dinning Room
    cards:
      - type: entities
        title: Entities
        entities:
          - sensor.top_slider_door
  - title: Master Bedroom
    cards:
      - type: media-control
        title: Parent's Bedroom Chromecast
        entity: media_player.chromecast0135
      - type: entities
        title: Closet
        entities:
          - switch.master_bedroom_closet
          - switch.ge_26931_smart_motion_switch_switch_4
  - title: Front Bedroom
    cards:
      - type: entities
        title: Light
        entities:
          - light.kids_light
      - type: entities
        title: Power
        entities:
          - switch.68102802dc4f22e873fa
  - title: Basement
    cards:
      - type: entities
        title: Basement Stairs
        entities:
          - switch.basement_stairs
          - switch.basement_stairs_motion
      - type: entities
        title: Basement Hall
        entities:
          - sensor.basement_smoke_detector
          - sensor.zooz_motion_detect_template
          - sensor.zooz_zse40_4_in_1_sensor_temperature
          - sensor.zooz_zse40_4_in_1_sensor_relative_humidity
          - sensor.zooz_motion_battery
          - sensor.first_alert_brk_brands_inc_zcombo_smoke_and_carbon_monoxide_detector_battery_level
      - type: entities
        title: Laundry Room
        entities:
          - binary_sensor.dryer_status
      - type: entities
        title: Office
        entities:
          - light.office_desk_lamp
      - type: entities
        title: Play Room
        entities:
          - media_player.basement_tv
      - type: thermostat
        entity: climate.basement_heat
      - type: history-graph
        title: 'Basement Temperature Graph'
        hours_to_show: 240
        refresh: 60
        entities:
          - sensor.zooz_zse40_4_in_1_sensor_temperature
          - sensor.dark_sky_temperature
      - type: history-graph
        title: 'Basement Humidity Graph'
        hours_to_show: 240
        refresh: 60
        entities:
          - sensor.zooz_zse40_4_in_1_sensor_relative_humidity
          - sensor.dark_sky_humidity
  - title: Outside
    cards:
      - type: picture-glance
        title: Front Door
        entities:
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
        camera_image: camera.front_door
      - type: entities
        title: Right Side Yard
        entities:
          - switch.outdoor_right_yard
      - type: entities
        title: Front Yard
        entities:
          - light.front_door
  - icon: mdi:weather-partly-cloudy
    title: Weather
    cards:
      - type: picture-entity
        entity: camera.bos_weather_radar
      - type: weather-forecast
        entity: weather.dark_sky
      - type: history-graph
        title: 'Current Temperature'
        hours_to_show: 48
        entities:
          - sensor.current_temp  
      - type: entities
        title: Sensors
        entities:
            - sun.sun
            - sensor.moon
            - sensor.bad_weather_sensor
            - sensor.dark_sky_temperature
            - sensor.dark_sky_apparent_temperature
            - sensor.dark_sky_humidity
            - sensor.dark_sky_cloud_coverage
            - sensor.dark_sky_precip
            - sensor.dark_sky_precip_probability
            - sensor.dark_sky_precip_intensity
            - sensor.dark_sky_nearest_storm_distance
            - sensor.dark_sky_wind_speed
            - sensor.dark_sky_wind_bearing
            - sensor.dark_sky_visibility
            - sensor.dark_sky_ozone
            - sensor.dark_sky_pressure
            - sensor.dark_sky_dew_point
  - icon: mdi:traffic-light
    title: Traffic
    cards:
      - type: glance
        title: Commute Times
        entities:
          - sensor.my_morning_commute
          - sensor.my_evening_commute
      - type: picture-entity
        entity: camera.rt_37_towards_warwick
      - type: picture-entity
        entity: camera.295_exit_1
      - type: picture-entity
        entity: camera.295_exit_6