- id: basement_hall_motion
  alias: "Motion Detected in Basement Hall - Turn on Stair Lights"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.zooz_motion_detect_template
      from: "standby"
      to: "motion detected"
  action:
    service: switch.turn_on
    entity_id: switch.basement_stairs
- alias: Turn off basement stairs light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.zooz_motion_detect_template
    to: 'standby'
    for:
      minutes: 3
  action:
    service: switch.turn_off
    entity_id: switch.basement_stairs
- alias: Motion in House - Turn on Kitchen
  trigger:
    - platform: state
      entity_id: switch.basement_stairs
      to: 'on'
    - platform: state
      entity_id: sensor.zooz_motion_detect_template
      to: 'motion detected'
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
  condition:
    condition: or
    conditions:
      - condition: time
        after: '23:00:00'
      - condition: sun
        before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.stove_light
- alias: Turn on Basement Heat AM
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.current_temp
        below: 66
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 68
        hvac_mode: heat
- alias: Turn on Basement Heat temp outside
  trigger:
    - platform: numeric_state
      entity_id: sensor.current_temp
      below: 66
  condition:
    condition: and
    conditions:
      - condition: time
        after: '08:00:00'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 68
        hvac_mode: heat
- alias: Reset Basement Heat
  trigger:
    - platform: time
      at: '00:15:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 60
        hvac_mode: heat