#
# Lights
#
- id: basement_hall_motion
  alias: "Motion Detected in Basement Hall - Turn on Stair Lights"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_hall_motion_detection
      to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.basement_stairs
- alias: Turn off basement stairs light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.basement_hall_motion_detection
    to: 'off'
    for:
      minutes: 3
  action:
    service: switch.turn_off
    entity_id: switch.basement_stairs
- alias: Motion in House - Turn on Kitchen
  trigger:
    - platform: state
      entity_id: switch.basement_stairs
      to: 'on'
    - platform: state
      entity_id: binary_sensor.basement_hall_motion_detection
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_bedroom_door_contact
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: time
        after: '23:00:00'
      - condition: sun
        before: sunrise
  action:
    - service: light.turn_on
      data:
        entity_id: light.stove_light

#
# Water Leaks
#

- alias: Water Leak at Slider
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_slider_wl_water_leak
      from: "off"
      to: "on"
  action:
    - service: notify.family
      data_template:
        message: "Water detected at basement slider"
    - service: notify.alexa_media
      data_template:
        target: 
          - media_player.basement_dot
          - media_player.living_room_show
          - media_player.parent_s_bedroom_dot
        message: "Water detected at basement slider"
        data:
          type: "announce"
- alias: Water Leak at Water Heater
  trigger:
    - platform: state
      entity_id: binary_sensor.water_heater_wl_water_leak
      from: "off"
      to: "on"
  action:
    - service: notify.family
      data_template:
        message: "Water detected at water heater"
    - service: notify.alexa_media
      data_template:
        target: 
          - media_player.basement_dot
          - media_player.living_room_show
          - media_player.parent_s_bedroom_dot
        message: "Water detected at water heater"
        data:
          type: "announce"
- alias: Water Leak at Outpipe
  trigger:
    - platform: state
      entity_id: binary_sensor.outpipe_wl_water_leak
      from: "off"
      to: "on"
  action:
    - service: notify.family
      data_template:
        message: "Water detected at basement outpipe"
    - service: notify.alexa_media
      data_template:
        target: 
          - media_player.basement_dot
          - media_player.living_room_show
          - media_player.parent_s_bedroom_dot
        message: "Water detected at basement outpipe"
        data:
          type: "announce"

#
# Basement Heat
#

- alias: Turn on Basement Heat AM
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.current_temp
        below: 50
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: binary_sensor.basement_slider_contact
        state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 65
        hvac_mode: heat
- alias: Turn on Basement Heat temp outside
  trigger:
    - platform: numeric_state
      entity_id: sensor.current_temp
      below: 50
  condition:
    condition: and
    conditions:
      - condition: time
        after: '08:00:00'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 58
        hvac_mode: heat
- alias: Reset Basement Heat
  trigger:
    - platform: time
      at: '00:15:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 50
        hvac_mode: heat
- alias: Turn off Basement Heat temp outside
  trigger:
    - platform: numeric_state
      entity_id: sensor.current_temp
      above: 66
  condition:
    condition: and
    conditions:
      - condition: time
        after: '08:00:00'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 50
        hvac_mode: heat
    - service: notify.family
      data:
        message: 'Turning off basement heat because the outside temp is above 66.'
- alias: Basement Slider Opened
  id: 'basement_slider_opened'
  trigger: 
  - platform: state
    entity_id: binary_sensor.basement_slider_contact
    to: 'on'
  action:
  - service: notify.me
    data:
      message: 'Basement Slider Door opened at {{now().strftime("%I:%M %p")}}'
- alias: Turn off basement heat if slider opened for 1 minute
  trigger:
    platform: state
    entity_id: binary_sensor.basement_slider_contact
    to: 'on'
    for:
      seconds: 60
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: climate.basement_heat
        state: 'heat'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.basement_heat
        temperature: 50
        hvac_mode: off
    - service: notify.family
      data:
        message: 'Turning off basement heat because the slider opened for more than 1 minute with the heat turned on.'