- alias: Dining Room Slider Opened
  id: 'dining_room_slider_opened'
  trigger: 
  - platform: state
    entity_id: binary_sensor.dining_room_slider_contact
    to: 'on'
  action:
  - service: notify.family
    data:
      message: 'Dining Room Slider opened at {{now().strftime("%I:%M %p")}}'

- id: dining_room_slider_opened_overnight
  alias: "Dining Room Slider Opened Overnight"
  trigger:
      platform: state
      entity_id: binary_sensor.dining_room_slider_contact
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: time
        after: '23:00:00'
      - condition: time
        before: '07:00:00'
  action:
    - service: notify.alexa_media
      data_template:
        target: 
          - media_player.basement_dot
          - media_player.living_room_show
          - media_player.parent_s_bedroom_dot
        message: "Dining Room Slider Opened"
        data:
          type: "announce"
- alias: Turn off upstairs heat if slider opened
  trigger:
    platform: state
    entity_id: binary_sensor.dining_room_slider_contact
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: climate.first_floor_heat
        state: 'heat'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.first_floor_heat
        temperature: 50
        hvac_mode: off
    - service: notify.family
      data:
        message: 'Turning off first floor heat because the dining room slider opened with the heat turned on.'