- alias: Outside Lights On
  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    - service: switch.turn_on
      entity_id: switch.outdoor_right_yard

- alias: Outside Lights Off
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    - service: switch.turn_off
      entity_id: switch.outdoor_right_yard

- alias: Holiday - Christmas Lighting On
  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_select.holiday
      state: 'Christmas'
  action:
    - service: switch.turn_on
      entity_id: switch.68102802dc4f22ef95b7

- alias: Holiday - Christmas Lighting Off
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_select.holiday
      state: 'Christmas'
  action:
    - service: switch.turn_off
      entity_id: switch.68102802dc4f22ef95b7
