- alias: Kids Light ready for bed
  trigger:
    - platform: time
      at: '18:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: light.lifx_set_state
      data:
        entity_id:
         - light.kids_light
        power: True
        brightness: 5
        color_temp: 285
        white_value: 255
- alias: Kids Light ready to play
  trigger:
    - platform: time
      at: '05:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: light.lifx_set_state
      data:
        entity_id:
         - light.kids_light
        brightness: 25
        rgb_color: [255,215,0]
        transition: 15
- alias: Kids Light ready to go
  trigger:
    - platform: time
      at: '06:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: light.lifx_set_state
      data:
        entity_id:
         - light.kids_light
        brightness: 100
        color_name: "green"
        transition: 15
- alias: Kids Light turn off
  trigger:
    - platform: time
      at: '07:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: light.lifx_set_state
      data:
        entity_id:
         - light.kids_light
        brightness: 255
        color_temp: 285
        white_value: 255
        power: false