- id: kitchen_stove_light_on_4pm
  alias: "Kitchen Stove Light on at 4pm"
  trigger:
    - platform: time
      at: '16:00:00'
  action:
    service: light.turn_on
    entity_id: light.stove_light
- id: kitchen_stove_light_off_time
  alias: "Kitchen Stove Light off at 11pm"
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    service: light.turn_off
    entity_id: light.stove_light
- alias: "Kitchen Stove Light reset for day"
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: lifx.set_state
      entity_id: light.stove_light
      data_template:
        brightness: 255
        transition: 10
- id: kitchen_stove_light_dim_time
  alias: "Kitchen Stove Light dim at 9pm"
  trigger:
    - platform: time
      at: '21:00:00'
  action:
    - service: light.turn_on
      entity_id: light.stove_light
      data_template:
        brightness: 90
        transition: 10
- id: kitchen_stove_light_off_10min
  alias: "Kitchen Stove Light turn off after 10 minutes"
  trigger:
    platform: state
    entity_id: light.stove_light
    to: 'on'
    for:
      minutes: 10
  condition:
    condition: time
    after: '23:00:00'
    before: '06:00:00'
  action:
    service: light.turn_off
    entity_id: light.stove_light