- alias: Dryer sense stop
  id: 'dryersensestop'
  trigger: 
  - platform: state
    entity_id: binary_sensor.dryer_status
    to: 'off'
    for:
      minutes: 2
  action:
  - service: notify.me
    data:
      message: 'The dryer has stopped at {{now().strftime("%I:%M %p")}}'
  - service: notify.wife
    data_template:
      message: 'Ello! The dryer has stopped at {{now().strftime("%I:%M %p")}}'
# - alias: Dryer sense stop tell Alexa
  # id: 'dryersensestopalexa'
  # trigger: 
  # - platform: state
    # entity_id: binary_sensor.dryer_status
    # to: 'off'
  # condition:
  # - condition: state
    # entity_id: 'sensor.sleep_mode'
    # state: 'awake'
  # action:
  # - service: notify.me_alexa
    # data:
      # message: 'The dryer has stopped at {{now().strftime("%I:%M %p")}}'