- alias: 'Night Lights'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
  action:
    service: light.turn_on
    entity_id:
      - group.livingroom_lights
      # - group.kitchen