- alias: Front Door Light On
  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.front_door
- alias: Front Door Light Off
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: light.turn_off
      entity_id: light.front_door
- alias: Front Door Light Off (Bug season)
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: sensor.season
      state: 'summer'
  action:
    - service: light.turn_off
      entity_id: light.front_door
- alias: "Front Door Motion Turn off Light after 10 minutes"
  trigger:
    platform: state
    entity_id: light.front_door
    to: 'on'
    for:
      minutes: 10
  condition:
    condition: time
    after: '23:00:00'
    before: '06:00:00'
  action:
    service: light.turn_off
    entity_id: light.front_door
- alias: Front Door Motion Turn on Light
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: template
      value_template: "{{ is_state('sensor.sleep_mode', 'all sleep') }}"
  action:
    - service: light.turn_off
      entity_id: light.front_door
- id: front_door_light_off_time
  alias: "Front Door Light off at 7am"
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    service: light.turn_off
    entity_id: light.front_door