- alias: Proactive Future Rain Notification
  id: 'gonna_rain'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.bad_weather_sensor
    to: "Yes"
  action:
    - service: notify.me
      data_template:
        title: "Storm nearby"
        message: "IT GONNA {{ states('sensor.dark_sky_precip') }}. Probability is at {{states.sensor.dark_sky_precip_probability.state}} percent. Nearest storm is {{states.sensor.dark_sky_nearest_storm_distance.state}} miles away."
        data: {"icon":"http://goo.gl/AU4Wf1"}