sensor:
  - platform: template
    sensors:
      basement_hall_multisensor_battery:
        friendly_name: "Basement Hall Multisensor Battery"
        value_template: "{% if states.zwave.zooz_zse40_4in1_sensor %}
            {{ states.zwave.zooz_zse40_4in1_sensor.battery_level }}
          {% else %}
            unknown
          {% endif %}"
        unit_of_measurement: '%'
        # entity_id: zwave.basement_hall_multisensor_2
        icon_template: >-
          {% set battery_level = states('sensor.basement_hall_multisensor_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}


binary_sensor:
  - platform: template
    sensors:
      basement_hall_multisensor_tamper:
        value_template: "{{ is_state('sensor.zooz_zse40_4in1_sensor_burglar', '3') }}"
        friendly_name: "Basement Hall Multisensor Tamper"
        device_class: safety
        # entity_id: sensor.basement_hall_multisensor_burglar

homeassistant:
  customize:

    sensor.zooz_zse40_4in1_sensor_alarm_level:
      hidden: true
    sensor.zooz_zse40_4in1_sensor_alarm_type:
      hidden: true
    sensor.zooz_zse40_4in1_sensor_burglar:
      hidden: true
    sensor.zooz_zse40_4in1_sensor_clock:
      hidden: true
    sensor.basement_hall_multisensor_sourcenodeid:
      hidden: true
    binary_sensor.basement_hall_multisensor_sensor:
      hidden: true
    sensor.zooz_zse40_4in1_sensor_emergency:
      hidden: true
    sensor.zooz_zse40_4in1_sensor_power_management:
      hidden: true
    sensor.zooz_motion_detect_template:
      hidden: true   



    sensor.zooz_zse40_4in1_sensor_luminance:
      friendly_name: Luminance
      icon: mdi:brightness-5
    sensor.zooz_zse40_4in1_sensor_relative_humidity:
      friendly_name: Humidity
      icon: mdi:water-percent
    sensor.zooz_zse40_4in1_sensor_temperature:
      friendly_name: Temperature
      icon: mdi:temperature-fahrenheit
    sensor.basement_hall_multisensor_battery:
      custom_ui_state_card: state-card-custom-ui
      friendly_name: Basement Hall Multisensor Battery
      group:
        group.basement_hall_multisensor:  
          friendly_name: Battery
        group.battery_group:  
          friendly_name: Basement Hall Multi

    binary_sensor.basement_hall_multisensor_tamper:
      friendly_name: Tamper
    sensor.zooz_motion_detect_template:
      custom_ui_state_card: state-card-custom-ui
      friendly_name: Basement Hall Motion
      group:
        group.basement_hall_multisensor:  
          friendly_name: Motion
        group.motionsensors:  
          friendly_name: Basement Hall


    group.basement_hall_multisensor:
      custom_ui_state_card: state-card-custom-ui
      group:
        group.motion_sensors:
          friendly_name: Basement Hall Alarm



group:
  basement_hall_multisensor:
    name: Basement Hall MultiSensor
    control: hidden
    entities:
      - sensor.zooz_motion_detect_template
      - binary_sensor.basement_hall_MultiSensor_tamper
      - sensor.basement_hall_MultiSensor_luminance
      - sensor.basement_hall_MultiSensor_relative_humidity
      - sensor.basement_hall_MultiSensor_temperature
      - sensor.basement_hall_MultiSensor_battery